# Generated by Django 5.1.3 on 2024-12-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_edit_own_portfolio', 'Can edit own portfolio')]},
        ),
    ]
