# Generated by Django 5.1.3 on 2024-12-04 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoCarrosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.JSONField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes_carrosel', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Seção Carrosel',
                'verbose_name_plural': 'Seções Carrosel',
            },
        ),
        migrations.CreateModel(
            name='SecaoDescritiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes_descritivas', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Seção Descritiva',
                'verbose_name_plural': 'Seções Descritivas',
            },
        ),
        migrations.CreateModel(
            name='SecaoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes_video', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Seção de Vídeo',
                'verbose_name_plural': 'Seções de Vídeo',
            },
        ),
    ]
