# Generated by Django 5.1.3 on 2024-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_secaocarrosel_secaodescritiva_secaovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
